### ISSUE TITLE
composer update出现问题

### ISSUE THREAD

**Issue by mazetao** [lea21st/leacmf#3]
composer.json文件中的  "topthink/framework": "^5.0"。
composer update出现却出现5.1版本。5.1版本里面没有start.php这个文件，导致无法正常访问项目

修改composer.json文件中的 "topthink/framework": "5.0.11"。
composer update成功，但是却无法访问项目，日志里面显示：

---------------------------------------------------------------
[ 2018-01-29T15:14:02+08:00 ] 127.0.0.1 127.0.0.1 GET /
[ error ] [2]scandir(D:\soft\laragon\www\leacmf/route/,D:\soft\laragon\www\leacmf/route/): ϵͳ�Ҳ���ָ�����ļ��� (code: 2)

---------------------------------------------------------------
[ 2018-01-29T15:14:07+08:00 ] 127.0.0.1 127.0.0.1 GET /public/index.php
[ error ] [2]scandir(D:\soft\laragon\www\leacmf/route/,D:\soft\laragon\www\leacmf/route/): ϵͳ�Ҳ���ָ�����ļ��� (code: 2)

---------------------------------------------------------------
[ 2018-01-29T15:14:09+08:00 ] 127.0.0.1 127.0.0.1 GET /
[ error ] [2]scandir(D:\soft\laragon\www\leacmf/route/,D:\soft\laragon\www\leacmf/route/): ϵͳ�Ҳ���ָ�����ļ��� (code: 2)。

本人使用apache+php7.1+mysql5.5

**Comment by lea21st** [comment]
topthink/framework": "^5.0"改成
topthink/framework": "5.1.*"
